### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attach' of undefined

### ISSUE THREAD

**Issue by sajclarke** [pinguinjkeke/php-class-tree#10]
[Enter steps to reproduce below:]

1. Open php file with classes (Codeigniter)
2. Open php file with html tags and no classes (Codeigniter)

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.2
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'attach' of undefined

```
At /Users/sajclarke/.atom/packages/php-class-tree/lib/php-class-tree.coffee:31

TypeError: Cannot read property 'attach' of undefined
  at PhpClassTree.attach (/Users/sajclarke/.atom/packages/php-class-tree/lib/php-class-tree.coffee:31:14)
  at Function.Main.getPhpClassTreeByEditor (/Users/sajclarke/.atom/packages/php-class-tree/lib/php-class-tree.coffee:252:20)
  at /Users/sajclarke/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)

```

### Commands

```
     -9:47.1.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -6:35.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:33.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:32.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:32.2.0 php-class-tree:build (atom-text-editor.editor)
     -5:39.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -5:38.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
php-class-tree, v1.0.0
todo-show, v0.13.0

# Dev
No dev packages
```

**Comment by Goddard** [comment]
Same problem here.  I work with Laravel and this happens every time I try and open my routes.php file.  Nothing special here and not a class.

**Comment by Braunson** [comment]
+1 Same issue here, accept it happens for a good 99% of PHP files in my project, super frustrating as no work is getting done.

**Comment by tminute** [comment]
+1


**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'attach' of undefined

```
At atom/packages/php-class-tree/lib/php-class-tree.coffee:31

TypeError: Cannot read property 'attach' of undefined
  at PhpClassTree.attach (/Users/t/.atom/packages/php-class-tree/lib/php-class-tree.coffee:31:14)
  at Function.Main.getPhpClassTreeByEditor (/Users/t/.atom/packages/php-class-tree/lib/php-class-tree.coffee:252:20)
  at atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:306:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:300:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:271:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:388:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:458:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.2
aligner-php, v1.0.0
angularjs, v0.3.0
angularjs-snippets, v0.10.18
atom-minify, v0.2.2
atom-peterjohnhunt-snippets, v1.5.1
atom-snippets, v0.1.1
atom-wordpress, v0.3.0
autocomplete-sass, v0.1.0
color-picker, v2.0.11
column-select, v0.2.0
css-color-underline, v1.0.1
css-snippets, v0.8.0
javascript-snippets, v1.0.0
linter-csslint, v1.0.5
linter-php, v1.0.3
minimap, v4.13.1
oblique-strategies, v0.2.0
pigments, v0.11.0
recent-projects, v0.8.3
sass-watch, v0.3.1
select-rectangle, v1.0.2
selector-to-tag, v0.4.1
tree-ignore, v0.2.6
tree-view-breadcrumb, v0.6.2
tree-view-filter, v0.3.7
tree-view-open-files, v0.2.4
w3c-validation, v0.2.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by bweston92** [comment]
+1 all I have is the following code

```
<?php

$a = function ($a) : string {
  return $a;
};

var_dump($a('1'));
var_dump($a(1));
```

**Comment by dorian-marchal** [comment]
Same here :+1:

**Comment by diego-vieira** [comment]
:+1:

**Comment by sculy** [comment]
same here at arch linux, I don't know the circunstances I made before this happens, but when it does it's always when I try to switch tabs

[Enter steps to reproduce below:]

1. I think I made a Build with the php-class-tree package to show up things
2. I've toggled the sidebar because I didn't wanted to see it anymore
3 . I've tried to switch tabs and I was unable to do it, and I got the error

(sorry for my bad english)

**Atom Version**: 1.0.19
**System**: "Arch Linux"
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /home/sculy/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (/home/sculy/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (/home/sculy/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
  at /home/sculy/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:314:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:308:19)
  at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:279:21)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:396:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:466:16)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:443:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:01.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:55.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:47.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:46.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:43.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:43.8.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:40.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:38 core:save (atom-text-editor.editor.is-focused)
     -0:34.7.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:17.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.1.0 settings-view:open (atom-text-editor.editor)
  4x -0:11.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar",
      "tool-bar-main",
      "linter-flake8",
    ],
    "autoHideMenuBar": true,
    "projectHome": "/home/sculy/dev",
    "themes": [
      "atom-material-ui",
      "monokai-syntax-for-one-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
atom-beautify, v0.28.16
atom-material-ui, v0.7.1
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v0.10.3
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
color-picker, v2.0.13
editorconfig, v1.2.2
file-icons, v1.6.11
highlight-selected, v0.10.1
html-entities, v0.4.0
hyperclick, v0.0.32
imdone-atom, v1.1.53
language-arduino, v0.3.1
language-ipynb, v1.3.0
language-pfm, v0.82.0
linter, v1.10.0
linter-clang, v3.3.0
linter-csslint, v1.1.0
linter-php, v1.1.1
linter-pylint, v1.0.3
linter-ruby, v1.2.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-linter, v1.0.0
monokai-syntax-for-one-dark, v0.2.2
nuclide-remote-projects, v0.0.32
php-getters-setters, v0.5.5
phpunit, v1.2.0
python-tools, v0.6.5
travis-ci-status, v0.18.0
typewriter, v0.3.5

# Dev
No dev packages
```

**Comment by d2s** [comment]
Steps to reproduce below:

1. Open multiple PHP files.
2. Click on the PHP Class Tree elements.
3. Close the active file tab.
4. When editor automatically moves different file, Atom error dialog appears.

**Atom Version**: 1.3.0
**System**: Ubuntu 14.04.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'attach' of undefined

```
At /home/d2s/.atom/packages/php-class-tree/lib/php-class-tree.coffee:31

TypeError: Cannot read property 'attach' of undefined
    at PhpClassTree.attach (/home/d2s/.atom/packages/php-class-tree/lib/php-class-tree.coffee:31:14)
    at Function.Main.getPhpClassTreeByEditor (/home/d2s/.atom/packages/php-class-tree/lib/php-class-tree.coffee:252:20)
    at /home/d2s/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /opt/atom/resources/app.asar/src/pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/opt/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app.asar/src/pane.js:316:21)
    at Pane.module.exports.Pane.activateItemAtIndex (/opt/atom/resources/app.asar/src/pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (/opt/atom/resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/opt/atom/resources/app.asar/src/pane.js:391:16)
    at Pane.module.exports.Pane.destroyItem (/opt/atom/resources/app.asar/src/pane.js:453:16)
    at Pane.module.exports.Pane.destroyActiveItem (/opt/atom/resources/app.asar/src/pane.js:433:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:641:35)
    at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/opt/atom/resources/app.asar/src/workspace.js:680:21)
    at atom-workspace.commandRegistry.add.core:close (/opt/atom/resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:50.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc"
    ],
    "projectHome": "/home/d2s/git"
  },
  "php-class-tree": {}
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
language-docker, v1.1.6
linter, v1.11.3
linter-clang, v3.3.0
markdown-preview-plus, v2.2.2
minimap, v4.18.2
pretty-json, v0.4.1
tree-view-filter, v0.3.9
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```
