### ISSUE TITLE
Uncaught Error: You must provide TextEditor

### ISSUE THREAD

**Issue by blakestein** [pinguinjkeke/php-class-tree#13]
I opened the command palette and ran PHP Class Tree: Build 

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught Error: You must provide TextEditor

```
At /Users/blakethompson/.atom/packages/php-class-tree/lib/php-class-tree.coffee:231

Error: You must provide TextEditor
  at Function.Main.getPhpClassTreeByEditor (/Users/blakethompson/.atom/packages/php-class-tree/lib/php-class-tree.coffee:231:17)
  at Main.build (/Users/blakethompson/.atom/packages/php-class-tree/lib/php-class-tree.coffee:227:33)
  at atom-workspace.<anonymous> (/Users/blakethompson/.atom/packages/php-class-tree/lib/php-class-tree.coffee:219:69)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:02.7.0 command-palette:toggle (div.settings-view.pane-item)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 php-class-tree:build (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-gfm",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "atom-jshint",
      "symbols-tree-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ]
  },
  "php-class-tree": {
    "displayOnRight": true
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v1.1.6
language-drupal, v0.4.2
language-php, v0.28.0
linter, v1.2.4
linter-php, v1.0.2
linter-phpmd, v1.0.0
php-class-tree, v1.0.0
seti-syntax, v0.4.0
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by pniederlag** [comment]
+1
