### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attach' of undefined

### ISSUE THREAD

**Issue by ken-master** [pinguinjkeke/php-class-tree#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'attach' of undefined

```
At C:\Users\ken\.atom\packages\php-class-tree\lib\php-class-tree.coffee:40

TypeError: Cannot read property 'attach' of undefined
    at PhpClassTree.attach (C:\Users\ken\.atom\packages\php-class-tree\lib\php-class-tree.coffee:40:27)
    at Function.Main.getPhpClassTreeByEditor (C:\Users\ken\.atom\packages\php-class-tree\lib\php-class-tree.coffee:314:22)
    at C:\Users\ken\.atom\packages\php-class-tree\lib\php-class-tree.coffee:253:31
    at Emitter.module.exports.Emitter.emit (C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\ken\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
laravel, v0.7.0
linter-php, v1.0.2

# Dev
No dev packages
```

**Comment by rugk** [comment]
Seems to be a duplicate of https://github.com/pinguinjkeke/php-class-tree/issues/20.
