### ISSUE TITLE
Uncaught TypeError: Cannot read property 'detach' of undefined

### ISSUE THREAD

**Issue by spencerthayer** [pinguinjkeke/php-class-tree#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /Users/spencerthayer/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (/Users/spencerthayer/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (/Users/spencerthayer/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at /Users/spencerthayer/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:316:21)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:391:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:641:35)
    at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:680:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -6:50.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:49.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:49.1.0 core:paste (atom-text-editor.editor.is-focused)
 11x -6:48.4.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -6:46.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:10.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:59.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:58.7.0 core:paste (atom-text-editor.editor.is-focused)
     -4:56.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -4:56.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -4:54.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:52.4.0 core:cut (atom-text-editor.editor.is-focused)
  5x -4:52.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:47.9.0 core:paste (atom-text-editor.editor.is-focused)
  3x -4:43 core:save (atom-text-editor.editor.is-focused)
 19x -0:29.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "flatland"
    ],
    "disabledPackages": [
      "Tern",
      "Tern",
      "git-blame",
      "atom-autocomplete-php",
      "eval-javascript"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-beautify, v0.28.19
atom-jshint, v2.0.0
atom-less, v0.1.9
atom-material-ui, v0.8.0
atom-minify, v0.7.1
autocomplete-emojis, v2.2.2
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-phpunit, v1.0.2
autocomplete-python, v1.2.4
autohide-tree-view, v0.25.1
cakephp-snippets, v0.6.1
cakephp3-snippets, v0.5.0
clipboard-plus, v0.5.1
color-picker, v2.0.14
css-snippets, v0.9.0
drunken-php, v0.2.1
drupal, v1.8.0
drupal-cinc, v0.0.3
drupal-info-file, v1.5.1
editorconfig, v1.2.2
flatland, v0.16.0
highlight-selected, v0.11.1
hyperclick-php, v0.2.1
javascript-snippets, v1.0.0
json-schema, v0.1.15
language-htaccess, v0.1.1
language-javascript-better, v1.7.1
language-php, v0.36.0
last-cursor-position, v0.9.0
less-compiler, v0.6.2
linter, v1.11.3
linter-less, v2.3.3
minimap, v4.19.0
node-debugger, v1.3.2
open-recent, v4.0.1
php-cs-fixer, v2.5.1
php-debug, v0.1.4
php-introspector, v1.0.0
pigments, v0.19.5
project-manager, v2.6.5
selector-to-tag, v0.4.1
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by spencerthayer** [comment]
I'll be uninstalling for the time being. Far too many errors to make coding possible.

**Comment by mryanb** [comment]
Same issues here.

**Comment by manoelt** [comment]
+1

**Comment by alimoosavi15** [comment]
Same here

**Comment by n1c01a5** [comment]
:+1:

**Comment by spencerthayer** [comment]
Anyone figure out a fix?

**Comment by rugk** [comment]
Also seems to appear when switching tabs now.

Interesting entries in the dev console too:
![classerror](https://cloud.githubusercontent.com/assets/11966684/12536114/00889c5e-c29b-11e5-9616-c645ee5d3577.PNG)

**Comment by rugk** [comment]
[Enter steps to reproduce below:]

0. The class tree was not shown.
1. A previous file was opened in Atom and I deleted it. Therefore the tab got closed.
2. I closed another tab (settings).

**Atom Version**: 1.4.0
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.4


### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:44

TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:316:21)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:391:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:453:16)
    at atom-tabs.TabBarView.onClick (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
  2x -8:28.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:26.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:26.8.0 php-cs-fixer:fix (atom-text-editor.editor)
     -7:38.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -7:36.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:36.1.0 php-cs-fixer:fix (atom-text-editor.editor)
     -3:14 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:11.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:10.8.0 php-cs-fixer:fix (atom-text-editor.editor)
     -3:03.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:00.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:00.0 php-cs-fixer:fix (atom-text-editor.editor)
     -0:17.2.0 core:paste (atom-text-editor#php-cs-fixer.executablePath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      [...],
      "atom-autocomplete-php"
    ],
    "packagesWithKeymapsDisabled": [
      "regex-railroad-diagram"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
[...]
autocomplete-php, v0.3.7
[...]
linter-php, v1.1.6
linter-phpmd, v1.3.2
[...]
php-class-tree, v1.0.0
php-cs-fixer, v2.5.2
php-debug, v0.2.1

# Dev
No dev packages
```

**Comment by AtomskJD** [comment]
+1
