### ISSUE TITLE
Uncaught TypeError: Cannot read property 'detach' of undefined

### ISSUE THREAD

**Issue by rugk** [pinguinjkeke/php-class-tree#26]
[Enter steps to reproduce below:]

0. The class tree was not shown.
1. A previous file was opened in Atom and I deleted it. Therefore the tab got closed.
2. I closed another tab (settings).

**Atom Version**: 1.4.0
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.4

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:44

TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at file:///D:/Users/%username%/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:316:21)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:391:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:453:16)
    at atom-tabs.TabBarView.onClick (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
  2x -8:28.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:26.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:26.8.0 php-cs-fixer:fix (atom-text-editor.editor)
     -7:38.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -7:36.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:36.1.0 php-cs-fixer:fix (atom-text-editor.editor)
     -3:14 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:11.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:10.8.0 php-cs-fixer:fix (atom-text-editor.editor)
     -3:03.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:00.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:00.0 php-cs-fixer:fix (atom-text-editor.editor)
     -0:17.2.0 core:paste (atom-text-editor#php-cs-fixer.executablePath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      [...],
      "atom-autocomplete-php"
    ],
    "packagesWithKeymapsDisabled": [
      "regex-railroad-diagram"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
[...]
autocomplete-php, v0.3.7
[...]
linter-php, v1.1.6
linter-phpmd, v1.3.2
[...]
php-class-tree, v1.0.0
php-cs-fixer, v2.5.2
php-debug, v0.2.1

# Dev
No dev packages
```

**Comment by rugk** [comment]
Seems to be a duplicate of https://github.com/pinguinjkeke/php-class-tree/issues/20.

**Comment by dinan354** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /C:/Users/HiddenPC/.atom/packages/php-class-tree/lib/php-class-tree.coffee:44

TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (file:///C:/Users/HiddenPC/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (file:///C:/Users/HiddenPC/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at file:///C:/Users/HiddenPC/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\src\pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\HiddenPC\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
     -3:56.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:56.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:55.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:44.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:44.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -3:44.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:44.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -3:44.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:44.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
 14x -3:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:23.5.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -3:18 core:move-right (atom-text-editor.editor.is-focused)
     -3:17.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:17.4.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -1:34 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-numix-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-material-numix-syntax, v0.2.1
atom-material-ui, v0.8.1
color-picker, v2.1.1
css-snippets, v0.9.0
css-specificity, v0.2.2
css-spy, v0.5.1
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
laravel, v0.7.0
laravel-snippets, v2.1.0
minimap, v4.19.0
php-cs-fixer, v2.5.2
pigments, v0.23.1
polymerjs-snippets, v2.1.0

# Dev
No dev packages
```

**Comment by summit-web** [comment]
I see this issue was opened in January - and I have suddenly started receiving this error now in July 2016. Atom says that the issue has been reported already so I won't re-post it but wondered whether anyone here could provide an update (if not I'll have to uninstall the extension).
