### ISSUE TITLE
Uncaught TypeError: XRegExp is not a function

### ISSUE THREAD

**Issue by Arcesilas** [pinguinjkeke/php-class-tree#27]
Steps to reproduce:

1. Click install button for php-class-tree package

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: XRegExp is not a function

```
At /home/olivier/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6

TypeError: XRegExp is not a function
    at Object.<anonymous> (/home/olivier/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6:19)
    at Object.<anonymous> (/home/olivier/.atom/packages/php-class-tree/lib/php-class-tree.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:220:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:302:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "metrics",
      "spell-check",
      "atom-local-export",
      "atom-oss-license",
      "symbols-view",
      "markdown-scroll-sync",
      "markdown-preview-plus",
      "php-extract-method",
      "php-debug",
      "php-cs-fixer",
      "file-watcher",
      "php-integrator-annotations",
      "php-integrator-autocomplete-plus",
      "php-integrator-base",
      "php-integrator-navigation",
      "php-integrator-symbol-viewer",
      "php-integrator-tooltips"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.7
docblockr, v0.7.3
language-blade, v0.20.0
laravel, v0.7.0
linter, v1.11.3
linter-php, v1.2.0
linter-twig, v0.1.0
php-twig, v4.0.0
project-manager, v2.7.6
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by rnolan** [comment]
Same issue:

[Enter steps to reproduce below:]

1. Click install button for php-class-tree package
2. Open php file
3. Open command pallete
4. Run PHP Class Tree: Build

Error also shows up in debug console when viewing installed packages

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Failed to activate the php-class-tree package

```
At XRegExp is not a function

TypeError: XRegExp is not a function
    at Object.<anonymous> (/Users/ricardonolan/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6:19)
    at Object.<anonymous> (/Users/ricardonolan/.atom/packages/php-class-tree/lib/php-class-tree.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.4.0 php-class-tree:build (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docs-snippets, v0.8.0
git-go, v1.0.1
php-class-tree, v1.0.0
php-cs-fixer, v2.5.6
symbol-gen, v1.0.0
terminal-panel, v1.14.1
tualo-git-context, v0.6.17

# Dev
No dev packages
```

**Comment by peter-trerotola** [comment]
Happening for me too.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: XRegExp is not a function

```
At /Users/petros/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6

TypeError: XRegExp is not a function
    at Object.<anonymous> (/Users/petros/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6:19)
    at Object.<anonymous> (/Users/petros/.atom/packages/php-class-tree/lib/php-class-tree.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:220:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:19)
    at PackageDetailView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:269:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:262:83)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -5:18.2.0 terminal-plus:toggle (atom-text-editor.editor.mini.is-focused)
     -1:18.3.0 pane:show-next-item (atom-text-editor.editor.mini.is-focused)
 10x -1:12.6.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "rest-client",
      "vim-mode-plus-ex-mode",
      "vim-mode-plus",
      "php-integrator-symbol-viewer"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-symfony2, v0.2.1
autocomplete-php, v0.3.7
php-composer-completion, v0.3.4
php-integrator-annotations, v0.3.2
php-integrator-autocomplete-plus, v0.6.0
php-integrator-base, v0.7.2
php-integrator-call-tips, v0.2.2
php-integrator-navigation, v0.6.1
php-integrator-tooltips, v0.5.0
symfony-snippets, v0.3.0
terminal-plus, v0.14.5
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by eduardoleal** [comment]
+1

**Atom Version:** 1.6.0
**System:** Ubuntu 15.10
**Thrown From:** php-class-tree package, v1.0.0

**Comment by drlenux** [comment]
+2

**Comment by dreamingodd** [comment]
+3
Atom: 1.6.2
System: Max OS 10.9.5

**Comment by seanmars** [comment]
+1
Atom Version: 1.7.2
System: Win 7 64 bit
Thrown From: php-class-tree package, v1.0.0

**Comment by seanbuscay** [comment]
Hi all, I have this working for myself so far by changing  `{XRegExp} = require 'xregexp'` to  `XRegExp = require 'xregexp'` on the line in the link to code below:

https://github.com/pinguinjkeke/php-class-tree/blob/fd5cd01f65d65ecc89d639e0116fe6e934a559e0/lib/php-class-tree.coffee#L1

I hope this may help.

**Comment by markkuit** [comment]
Does anybody know of an alternative package which achieves the same feature? php-class-tree seems to be way too buggy to reliably code with at the moment.

**Comment by RifuI** [comment]
Agreed, I was able to get it to work after using @seanbuscay's fix. After which it worked for a very limited time and then I could not toggle the tree any more.

**Comment by sejbr** [comment]
@markkuit @RifuI 
This https://atom.io/packages/symbols-tree-view works similarly. Not a tree per say but works well enough. Unless you already found something better. Would love a link then :).

**Comment by RifuI** [comment]
Thanks, I didn't find anything else better. Close to dropping Atom for lack of these most basic features. This kind of thing should be core IMO because it's almost a requirement for working with larger codebases.

**Comment by camel-chased** [comment]
same

**Comment by markkuit** [comment]
I actually found symbols-tree-view to almost perfectly match what I was looking for (it's just missing the tree-style view). I'm rusty with coffeescript so I don't really know how hard it would be to implement.

**Comment by fedorovstas** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: XRegExp is not a function

```
At /home/nomad/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6

TypeError: XRegExp is not a function
    at Object.<anonymous> (/home/nomad/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6:19)
    at Object.<anonymous> (/home/nomad/.atom/packages/php-class-tree/lib/php-class-tree.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:220:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:175:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:306:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:672:27)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:460:26
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -9:48.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:48.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:45.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:31.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:29.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:14.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -8:12.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -8:05.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:18.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
file-type-icons, v1.3.0
highlight-selected, v0.11.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
minimap, v4.23.5
minimap-highlight-selected, v4.4.0
pigments, v0.26.3
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by mcdado** [comment]
[Enter steps to reproduce below:]

1. Open a PHP class file
2. Run the php class tree command.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Failed to activate the php-class-tree package

```
At XRegExp is not a function

TypeError: XRegExp is not a function
    at Object.<anonymous> (/Users/David/.atom/packages/php-class-tree/lib/php-class-tree.coffee:6:19)
    at Object.<anonymous> (/Users/David/.atom/packages/php-class-tree/lib/php-class-tree.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:52.3.0 symbols-tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:24.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:23.2.0 project-find:show (atom-text-editor.editor.mini.is-focused)
     -1:16 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 php-class-tree:build (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-tidy",
      "linter-sass-lint",
      "deprecation-cop",
      "linter-jscs",
      "linter-jshint",
      "w3c-validation"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "themes": [
      "native-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9
atom-html-preview, v0.1.19
autocomplete-html-entities, v0.1.0
color-picker, v2.1.1
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.13
html-entities, v0.4.0
language-apache, v1.5.0
language-gitattributes, v1.0.3
language-ignore, v1.4.4
language-ini, v1.16.0
language-log, v1.4.0
language-smarty, v1.7.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-htmlhint, v1.1.4
linter-jsonlint, v1.2.5
linter-php, v1.2.0
linter-scss-lint, v3.0.4
linter-xmllint, v1.3.4
minimap, v4.24.3
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-linter, v1.1.1
minimap-selection, v4.4.0
native-ui, v0.18.2
php-class-tree, v1.0.0
php-cs-fixer, v2.5.6
ssh-config, v0.10.1
symbols-tree-view, v0.13.0
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by mcdado** [comment]
Anyway, the need for many of these plugins would be alleviated if the built-in symbols generation and navigation worked! <kbd>cmd</kbd>+<kbd>R</kbd> shows class properties (that are very little useful to me, anyone that really needs them?) and misses many methods for some reason!
