### ISSUE TITLE
Failed to activate the php-class-tree package

### ISSUE THREAD

**Issue by igogo5yo** [pinguinjkeke/php-class-tree#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.11
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v0.2.0

### Stack Trace

Failed to activate the php-class-tree package

```
At Cannot read property 'getText' of undefined

TypeError: Cannot read property 'getText' of undefined
  at Object.module.exports.build (/Users/ihor/.atom/packages/php-class-tree/lib/php-class-tree.coffee:159:18)
  at Object.module.exports.activate (/Users/ihor/.atom/packages/php-class-tree/lib/php-class-tree.coffee:152:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:06.9.0 command-palette:toggle (atom-pane.pane.active)
  4x -0:03.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 php-class-tree:build (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "jshint",
      "php-cs-fixer",
      "php-introspector"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yii, v0.4.0
atom-yii2, v0.0.0
autocomplete-php, v0.3.6
emmet, v2.3.10
language-babel, v0.8.1
language-javascript-jsx, v0.3.6
language-twig, v1.6.1
node-debugger, v1.1.0
open-github-from-npm, v0.1.0
php-class-tree, v0.2.0
php-getters-setters, v0.5.5
php-twig, v4.0.0
phpunit, v1.1.1
react, v0.12.0

# Dev
No dev packages
```

**Comment by pinguinjkeke** [comment]
It looks like you tried to create tree while no files opened.
It's fixed in 1.0.0
