### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by sunel** [pinguinjkeke/php-class-tree#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/sunel/.atom/packages/php-class-tree/lib/php-class-tree.coffee:37

TypeError: Cannot read property 'getGrammar' of undefined
  at PhpClassTree.toggle (/Users/sunel/.atom/packages/php-class-tree/lib/php-class-tree.coffee:37:44)
  at atom-workspace.<anonymous> (/Users/sunel/.atom/packages/php-class-tree/lib/php-class-tree.coffee:220:80)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/sunel/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Users/sunel/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/sunel/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Users/sunel/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -2:33.8.0 command-palette:toggle (atom-pane.pane.active)
 44x -2:30.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -2:12.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:07.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:06.1.0 fuzzy-finder:toggle-git-status-finder (atom-pane.pane.active)
  5x -2:03.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:01.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -1:59 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:49.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:49.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:45.9.0 command-palette:toggle (atom-pane.pane.active)
  9x -1:34.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:54 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:27.6.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.0 php-class-tree:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/sunel/Documents/Code"
  }
}
```

### Installed Packages

```coffee
# User
linter-php, v0.0.15
php-class-tree, v1.0.0
php-cs-fixer, v2.3.0

# Dev
No dev packages
```

**Comment by pinguinjkeke** [comment]
Can you provide the steps to reproduce?

**Comment by segadora** [comment]
I am getting the same error. Fresh atom installed on mint 17.1.

**Comment by pinguinjkeke** [comment]
Can you provide steps to reproduce?

**Comment by segadora** [comment]
1. Install atom
2. Install php-class-tree

Run CTRL + ALT + R
The error seems to have accured once on a laravel projekt. Afterwards it showed a list of methods in the class.

I am unable to provide a ready to run senario

**Comment by sunel** [comment]
I noticed one thing , when there is not php files opened and then Run CTRL + ALT + R this error occurs and something also when there is a php file.
