### ISSUE TITLE
Uncaught TypeError: Cannot read property 'detach' of undefined

### ISSUE THREAD

**Issue by calvinchoy** [pinguinjkeke/php-class-tree#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /Users/Karubin/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (/Users/Karubin/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (/Users/Karubin/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
  at /Users/Karubin/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "2-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".idea",
      "vendor",
      "storage",
      "tests",
      "doc"
    ],
    "disabledPackages": [
      "metrics",
      "wrap-guide",
      "atom-bootstrap3",
      "minimap-autohide"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "php-class-tree": {
    "displayOnRight": true
  }
}
```

### Installed Packages

```coffee
# User
2-dark-syntax, v0.1.1
atom-alignment, v0.12.1
atom-beautify, v0.28.7
autocomplete-php, v0.3.6
bootstrap-3-snippetset, v0.0.6
color-picker, v2.0.7
emmet, v2.3.10
git-plus, v5.2.2
highlight-selected, v0.10.1
language-blade, v0.14.0
language-viml, v0.2.0
line-jumper, v0.14.1
linter, v1.1.0
linter-jscs, v1.12.0
linter-php, v0.0.15
minimap, v4.10.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
php-class-tree, v1.0.0
php-cs-fixer, v2.3.0
pigments, v0.8.1
project-manager, v1.15.10
remote-atom, v1.2.6
seti-icons, v0.3.0
spacegray-dark-ui, v0.12.0
subword-navigation, v2.9.0
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by segadora** [comment]
+1

Happened when I deleted a reference and clicked CTRL + W

**Comment by nelson6e65** [comment]
I got the same issue :fire:, on Linux (Fedora 21), just changing to another tab.

```
/home/nmartell/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (/home/nmartell/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (/home/nmartell/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
  at /home/nmartell/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/local/share/atom/resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/local/share/atom/resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/usr/local/share/atom/resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/local/share/atom/resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activatePreviousItem (/usr/local/share/atom/resources/app.asar/src/pane.js:263:21)
  at Pane.module.exports.Pane.removeItem (/usr/local/share/atom/resources/app.asar/src/pane.js:372:16)
  at Pane.module.exports.Pane.destroyItem (/usr/local/share/atom/resources/app.asar/src/pane.js:442:16)
  at HTMLDivElement.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/local/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/local/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by Braunson** [comment]
Same issue here.. 

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At C:\Users\braunson\.atom\packages\php-class-tree\lib\php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (C:\Users\braunson\.atom\packages\php-class-tree\lib\php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (C:\Users\braunson\.atom\packages\php-class-tree\lib\php-class-tree.coffee:245:17)
  at C:\Users\braunson\.atom\packages\php-class-tree\lib\php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:238:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:302:21)
  at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:296:19)
  at Pane.module.exports.Pane.activateNextItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:257:21)
  at Pane.module.exports.Pane.removeItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:382:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:454:16)
  at Pane.module.exports.Pane.destroyActiveItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:431:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:600:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:639:21)
  at atom-workspace.atom.commands.add.core:close (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace-element.js:308:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\braunson\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -1:12.4.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:59.6.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:59.6.0 core:close (atom-text-editor.editor.is-focused)
  5x -0:54.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.2.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:47.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:26.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:cut (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.6.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.0.1
atom-beautify, v0.28.7
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
code-links, v0.3.11
color-picker, v2.0.7
devdocs, v0.2.1
docblockr, v0.7.2
editor-stats, v0.17.0
file-icons, v1.5.8
flex-tool-bar, v0.4.3
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.3.9
linter, v1.1.0
linter-php, v0.0.15
minimap, v4.10.2
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
pigments, v0.8.2
Remote-FTP, v0.7.1
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-git-modified, v0.5.10

# Dev
No dev packages
``

**Comment by Calcio** [comment]
[Enter steps to reproduce below:]

1. Install
2. Open an no class PHP file

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /home/calcio/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (/home/calcio/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (/home/calcio/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
  at /home/calcio/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:306:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:300:19)
  at Pane.module.exports.Pane.activateNextItem (/usr/share/atom/resources/app.asar/src/pane.js:261:21)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:386:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:458:16)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -5:52.7.0 php-debug:toggleDebugging (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:27.4.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
  2x -5:23.8.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -5:20.8.0 core:undo (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -5:13.1.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
  8x -5:09.6.0 core:undo (atom-text-editor.editor.is-focused)
     -5:01.8.0 php-debug:toggleDebugging (div.settings-view.pane-item)
     -4:56.6.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
     -4:54.5.0 core:undo (atom-text-editor.editor.is-focused)
     -1:17.8.0 grammar-selector:show (atom-text-editor.editor)
     -1:09.5.0 core:save (a.inline-block)
     -0:23.8.0 core:cancel (div.php-debug.php-debug-unified-view.pane-item.padded)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-class-tree"
    ]
  },
  "php-class-tree": {
    "displayOnRight": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.7.0
autocomplete-php, v0.3.6
php-analyser, v0.2.0
php-debug, v0.1.2

# Dev
No dev packages
```

**Comment by kevin39** [comment]
Any bugfix ?

**Comment by LukeXF** [comment]
Just installed this, but everything I try to click on returns this error

**Comment by diego-vieira** [comment]
+1 getting this a lot

**Comment by edomato** [comment]
Same here, has to disable this plugin for this error to stop happening, of course. :smile:

**Comment by gfviegas** [comment]
+1 even disabling package I still got this... idk but i think its a namespace trouble. php-class-tree has no support for namespaces yet, am I right?

**Comment by e5an** [comment]
Today I was getting a bunch of copies of this error popping up while not even looking at a PHP file or having one in my project. Uninstalled php-class-tree and not touching it again until this is confirmed fixed.

**Comment by gfviegas** [comment]
So did I @e5an
