### ISSUE TITLE
I was testing your plugin and this happen

### ISSUE THREAD

**Issue by diegollave** [pinguinjkeke/php-class-tree#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: 'php-class-tree' package, vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At C:\Users\Inspiron\.atom\packages\php-class-tree\lib\php-class-tree.coffee:34

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (C:\Users\Inspiron\.atom\packages\php-class-tree\lib\php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (C:\Users\Inspiron\.atom\packages\php-class-tree\lib\php-class-tree.coffee:245:17)
  at C:\Users\Inspiron\.atom\packages\php-class-tree\lib\php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:298:21)
  at tabs-tab.<anonymous> (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Inspiron\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -9:48.5.0 core:save (atom-text-editor.editor.is-focused)
     -9:47.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -9:47.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:46.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:24.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:23.9.0 core:save (atom-text-editor.editor.is-focused)
     -6:45.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:53.8.0 core:cut (atom-text-editor.editor.is-focused)
  2x -5:53.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:51.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:48.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:48.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:47.7.0 core:paste (atom-text-editor.editor.is-focused)
     -5:46 core:undo (atom-text-editor.editor.is-focused)
     -5:34 settings-view:open (atom-text-editor.editor.is-focused)
     -0:39.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-class-tree"
    ]
  },
  "php-class-tree": {
    "autoToggle": false,
    "displayOnRight": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7

# Dev
No dev packages
```

**Comment by pinguinjkeke** [comment]
Provide steps please.

**Comment by keyshooter** [comment]
Open a PHP with a class file, after that, i open a PHP without class, and then i go to change the atom theme, and then, the plugin crashes
Date: Tue, 30 Jun 2015 13:03:06 -0700
